server:
  port: 8084
spring:
  application:
    name: innovation
  datasource:
    url: jdbc:postgresql://localhost:5432/tax-dash-auth
    username: postgres
    password: stan
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:  
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties: 
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

  queue.name: taxdash.verification.queue
  exchange.name: taxdash.verification.exchange
  routing.key: taxdash.verification.key

amqp:
  deserialization:
    trust:
      all: true

email:
  owner:  ${EMAIL_USERNAME}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 day in milliseconds
  